[2023-05-23T19:36:34.201+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T19:36:34.207+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T19:36:34.208+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T19:36:34.208+0000] {taskinstance.py:1363} INFO - Starting attempt 10 of 10
[2023-05-23T19:36:34.209+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T19:36:34.215+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-01 00:00:00+00:00
[2023-05-23T19:36:34.221+0000] {standard_task_runner.py:55} INFO - Started process 15475 to run task
[2023-05-23T19:36:34.225+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpnkeu479d']
[2023-05-23T19:36:34.228+0000] {standard_task_runner.py:83} INFO - Job 57: Subtask load
[2023-05-23T19:36:34.239+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T19:36:34.279+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T19:36:34.325+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-23T19:36:34.327+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T19:36:34.333+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 88, in load
    cursor.execute(copy_sql)
psycopg2.errors.UndefinedFile: could not open file "/tmp/2019-04-01_new.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-05-23T19:36:34.342+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=load, execution_date=20190401T000000, start_date=20230523T193634, end_date=20230523T193634
[2023-05-23T19:36:34.349+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 57 for task load (could not open file "/tmp/2019-04-01_new.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 15475)
[2023-05-23T19:36:34.397+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T19:36:34.411+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
