[2023-05-23T13:16:56.557+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [queued]>
[2023-05-23T13:16:56.601+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [queued]>
[2023-05-23T13:16:56.603+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:16:56.603+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-23T13:16:56.604+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:16:56.622+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2019-04-04 00:00:00+00:00
[2023-05-23T13:16:56.630+0000] {standard_task_runner.py:55} INFO - Started process 3799 to run task
[2023-05-23T13:16:56.636+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'extract', 'scheduled__2019-04-04T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmp_9swbow3']
[2023-05-23T13:16:56.644+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask extract
[2023-05-23T13:16:56.681+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T13:16:56.854+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T13:16:56.958+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2019-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-04T00:00:00+00:00
[2023-05-23T13:16:56.960+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T13:16:56.961+0000] {logging_mixin.py:137} INFO - 2019-04-04
[2023-05-23T13:16:57.056+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 33, in extract
    csv_obj = src_client.get_object(Key=object_key)
AttributeError: 's3.Bucket' object has no attribute 'get_object'
[2023-05-23T13:16:57.075+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=extract, execution_date=20190404T000000, start_date=20230523T131656, end_date=20230523T131657
[2023-05-23T13:16:57.091+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task extract ('s3.Bucket' object has no attribute 'get_object'; 3799)
[2023-05-23T13:16:57.149+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T13:16:57.169+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-23T13:20:10.895+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [queued]>
[2023-05-23T13:20:10.911+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [queued]>
[2023-05-23T13:20:10.911+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:20:10.914+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-23T13:20:10.914+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:20:10.939+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2019-04-04 00:00:00+00:00
[2023-05-23T13:20:10.944+0000] {standard_task_runner.py:55} INFO - Started process 3976 to run task
[2023-05-23T13:20:10.966+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'extract', 'scheduled__2019-04-04T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpzn9h7ula']
[2023-05-23T13:20:10.979+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask extract
[2023-05-23T13:20:11.028+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T13:20:11.210+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.extract scheduled__2019-04-04T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T13:20:11.403+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2019-04-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-04T00:00:00+00:00
[2023-05-23T13:20:11.410+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T13:20:11.414+0000] {logging_mixin.py:137} INFO - 2019-04-04
[2023-05-23T13:20:11.714+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 33, in extract
    csv_obj = src_client.get_object(Bucket=src_bucket, Key=object_key)
AttributeError: 's3.Bucket' object has no attribute 'get_object'
[2023-05-23T13:20:11.744+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=extract, execution_date=20190404T000000, start_date=20230523T132010, end_date=20230523T132011
[2023-05-23T13:20:11.767+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task extract ('s3.Bucket' object has no attribute 'get_object'; 3976)
[2023-05-23T13:20:11.848+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T13:20:11.867+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
